# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56d32966143ae10c56b6a80825419eaee1dbb8d1f29e6a890f5d3ce27cfe45725a0d304237bb3b36f7e0bf6e2c230d7015d3ef96cecdc7f57a80ab9726fb839c

test:
  secret_key_base: 9c62cc173fd0d3864ba67d1282b5634708fd2c2226ac8e4d5638d49655f3aec80f5cfb436877790c91b6bd24bd41316b2e9b385e5e29e1e58e873f2589780fba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
